### ISSUE TITLE
How to hide the container window?

### ISSUE THREAD

**Issue by naiba** [inkyblackness/imgui-go-examples#1]
![QQ20190525-113503@2x.png](https://i.loli.net/2019/05/25/5ce8b7fa73f2c12365.png)

@dertseha

**Comment by naiba** [comment]
￼￼1. hide the container window, no title bar, transparent background.
2. create the main window, size as the hidden container window, resize as the hidden container window
3. all subwindows under the main window

I think this is a good solution.

**Comment by naiba** [comment]
Or it called [viewport](https://github.com/ocornut/imgui/issues/1542)? How can i set container's style( no title bar, transparent background)?

**Comment by dertseha** [comment]
Hello there and thank you for your message!
I yet haven't understood the question - Do you want to create a container that acts like a window, yet doesn't show up like a window? If this is the case, you can call `BeginChild()` (or the verbose variant) to create a container. You can do this also in the root "window".

**Comment by naiba** [comment]
Thank you for your help.

Yes, I want to create a root window just like inner windows:`Hello, world!` window. Not under the black sh*t. I follow the imgui-go's document, and no idea to use `BeginChild()`, can you tell me how to find the document about creating such a window?

**Comment by naiba** [comment]
@dertseha Thank you for your help.

Yes, I want to create a root window just like inner windows:Hello, world! window. Not under the black sh*t. I follow the imgui-go's document, and no idea to use BeginChild(), can you tell me how to find the document about creating such a window?

**Comment by naiba** [comment]
@dertseha Can you create an example with only the `Hello, world!` window? (Do not have the black container window `ImGui-Go`)

**Comment by naiba** [comment]
Hello @dertseha, I've edited `sdl.go` to set the root window's style. But when I set window flag `imgui.WindowFlagsNoTitleBar` it always opens in full-screen, how can I open it in normal size? Thank you.

**Comment by dertseha** [comment]
Sorry, I don't have much time currently to answer - I also don't know that much by heart as I experiment a lot on my own as well. (This library is a wrapper over the cpp library, after all :) )
You can have a look at the .cpp code of ImGui, especially the `DemoWindow` how to do things.

**Comment by dertseha** [comment]
Hello again - thank you for your patience. I was busy the past days and weeks, now I have more time again.
Are you still struggling with the code?

I'd also like to clarify what you want:
* First the application window - the one opened in `sdl.go` - what did you change here? Be aware that this window is under "your" control, and not of imgui. So, whatever you change there has no effect on imgui (and the other way round). Meaning, in your example screenshot, the window with title bar `ImGui-Go SDL2+OpenGL3 example` is handled in `sdl.go`.
* Then the imgui window - Do you want to create a container with some elements, and this container does not show up with a imgui title bar? meaning, in your example screenshot, the window with title bar `Hello, world!`, is handled by calling imgui functions.

**Comment by naiba** [comment]
Thanks @dertseha , I am still working on this, I have found these two points. However, I am having trouble creating a window that does not have a system window border and takes over the window zoom. This window open defaults to full screen display and cannot be displayed at a fixed size.

**Comment by dertseha** [comment]
This doesn't sound specific to imgui. Can you reproduce the issue with a simple test application?

I tried this application, which created a small floating window without system border:
```
package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/veandco/go-sdl2/sdl"
)

func main() {
	runtime.LockOSThread()

	err := sdl.Init(sdl.INIT_VIDEO)
	if err != nil {
		fmt.Printf("failed to initialize SDL2: %v", err)
		return
	}
	defer sdl.Quit()

	window, err := sdl.CreateWindow("Test", sdl.WINDOWPOS_CENTERED, sdl.WINDOWPOS_CENTERED, 1280, 720, sdl.WINDOW_BORDERLESS)
	if err != nil {
		fmt.Printf("failed to create window: %v", err)
		return
	}
	defer window.Destroy()

	renderer, err := sdl.CreateRenderer(window, -1, 0)
	if err != nil {
		fmt.Printf("failed to create renderer: %v", err)
		return
	}
	defer renderer.Destroy()

	renderer.Clear()

	window.UpdateSurface()

	<-time.After(10 * time.Second)
}
```

How does your `sdl.CreateWindow()` call look like?

**Comment by dertseha** [comment]
Addendum: To clarify: You wrote 
> But when I set window flag imgui.WindowFlagsNoTitleBar it always opens in full-screen

Did you pass `imgui.WindowFlagsNoTitleBar` to the function `sdl.CreateWindow()` ? Because this would explain the problem: `sdl.CreateWindow()` takes only constants from `sdl.WINDOW_*` - nothing from imgui. These are two separate libraries.

It just so happens that the constant `imgui.WindowFlagsNoTitleBar` has the same integer value as `sdl.WINDOW_FULLSCREEN` :)

**Comment by naiba** [comment]
Hello @dertseha, I've tested your code at my macOS Mojave, it shows nothing and quit after 10 seconds even set `window, err := sdl.CreateWindow("Test", sdl.WINDOWPOS_CENTERED, sdl.WINDOWPOS_CENTERED, 1280, 720, sdl.WINDOW_BORDERLESS|sdl.WINDOW_SHOWN|WINDOW_ALWAYS_ON_TOP)`. 
I am cleared they are two different libraries.

**Comment by dertseha** [comment]
OK, for me it displayed gray default color. With the following code it fills the window red:
```
package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/veandco/go-sdl2/sdl"
)

func main() {
	runtime.LockOSThread()

	err := sdl.Init(sdl.INIT_VIDEO)
	if err != nil {
		fmt.Printf("failed to initialize SDL2: %v", err)
		return
	}
	defer sdl.Quit()

	window, err := sdl.CreateWindow("Test", sdl.WINDOWPOS_CENTERED, sdl.WINDOWPOS_CENTERED, 1280, 720, sdl.WINDOW_BORDERLESS)
	if err != nil {
		fmt.Printf("failed to create window: %v", err)
		return
	}
	defer window.Destroy()

	renderer, err := sdl.CreateRenderer(window, -1, 0)
	if err != nil {
		fmt.Printf("failed to create renderer: %v", err)
		return
	}
	defer renderer.Destroy()

	renderer.Clear()
	renderer.SetDrawColor(255, 0, 0, 255)
	renderer.FillRect(&sdl.Rect{X: 0, Y: 0, W: 1280, H: 720})
	renderer.Present()

	window.UpdateSurface()

	<-time.After(10 * time.Second)
}

```
(added some drawing to the above example)

When you remove `sdl.WINDOW_BORDERLESS`, then the window will have the regular frame again.

**Comment by naiba** [comment]
@dertseha Stil shows nothing. even I remove `sdl.WINDOW_BORDERLESS` also not shows a regular frame.

**Comment by dertseha** [comment]
OK, then I don't know how to help you further. Please look for general, simple starter examples on the internet for creating a basic SDL window for your system.
When that is working, then play with the `sdl.WINDOW_BORDERLESS` flag.

Of course, if you have the imgui example running, you could also add the `sdl.WINDOW_BORDERLESS` flag there to try it out.

**Comment by naiba** [comment]
Alright, thank you very much. I also intend to modify from the example, I will keep this issue open, but you don't have to worry about it. I will continue to update my experimental results. I believe that removing the discordant border is a wish of many people.

**Comment by dertseha** [comment]
OK - still, I believe you need to play with the `sdl.WINDOW_BORDERLESS` flag. Tell me when you tested it.

**Comment by naiba** [comment]
LOL, Set `sdl.WINDOW_BORDERLESS` to `sdl.CreateWindow` function can hide the container window.
