### ISSUE TITLE
How can I attach imgui to an existing GLFW window?

### ISSUE THREAD

**Issue by adamthomason** [inkyblackness/imgui-go-examples#6]
I'm trying to implement imgui as a debug tool into my engine but struggling to understand how to attach imgui to an existing GLFW window instance. I've implemented a layer system after an initial window is created. Any help or advice here would be greatly appreciated!

**Comment by dertseha** [comment]
Hello there and thank you for your message!
With an existing window you have already a first step, this is good.
I'd say it comes down to re-create what is available in this examples repository.

I suspect most of `internal/platforms/glfw.go` you already have, so you need to focus on only what is necessary what is exposed via the `Platform` interface in `internal/example/Run.go` (match what your existing render loop has to this one, and add what's missing).

To get imgui running, you'll then need most/all of what is under `internal/renderers` - either the OpenGL2 or OpenGL3 variant, whichever you have in your application. Set it up like the corresponding `main.go` does.
Finally, get the whole loop running by looking at `internal/example/Run.go` and see what you are missing in your existing loop.

In essence, imgui is quite unobstrusive. You set it up separately, wire up the platform interface to the `IO` API, and put the render logic before you do the actual `SwapBuffer` (equivalent).

**Comment by adamthomason** [comment]
Thanks, @dertseha for the awesome advice. Have a great day!

**Comment by adamthomason** [comment]
In case anybody stumbles upon this issue and is interested in how I implemented the advice above, see https://github.com/adamthomason/expression/tree/master/layers/imgui

**Comment by airtonix** [comment]
> In case anybody stumbles upon this issue and is interested in how I implemented the advice above, see https://github.com/adamthomason/expression/tree/master/layers/imgui

link is dead.
